# Generated by Django 5.2 on 2026-02-01 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencevoyage',
            options={'ordering': ['legal_name']},
        ),
        migrations.AlterModelOptions(
            name='agencyapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'ordering': ['agence__legal_name', 'nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='succursale',
            options={'ordering': ['agence__legal_name', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['agence__legal_name', 'immatriculation']},
        ),
        migrations.RenameField(
            model_name='agencevoyage',
            old_name='adresse',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='agencevoyage',
            old_name='pays',
            new_name='company_country',
        ),
        migrations.RenameField(
            model_name='agencevoyage',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='agencevoyage',
            old_name='telephone',
            new_name='company_phone',
        ),
        migrations.RenameField(
            model_name='agencevoyage',
            old_name='nom',
            new_name='legal_name',
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='agencies/reps/'),
        ),
        migrations.AddField(
            model_name='agencyapplication',
            name='telephone_urgence_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agencevoyage',
            name='tour_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences', to='apps.touroperateur'),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='code_categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='code_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='company_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='etab_secondaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='otp_delivery',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='rne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='agencyapplication',
            index=models.Index(fields=['statut', 'created_at'], name='apps_agency_statut_a2eba0_idx'),
        ),
    ]
