# Generated by Django 5.2 on 2025-05-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencevoyage',
            name='user',
        ),
    ]
