# Generated by Django 5.2 on 2025-05-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_remove_agencevoyage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('details', models.TextField(blank=True)),
                ('premission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='b2b.premission')),
            ],
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='b2b.mission'),
        ),
    ]
