# Generated by Django 5.2 on 2025-05-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_touroperateur_succursale_agencevoyage_tour_operateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='heure_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
