# Generated by Django 5.2 on 2025-05-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0007_dossier_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordremission',
            name='bus',
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('MICROBUS', 'MICROBUS'), ('4x4', '4X4')], max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='b2b.agencevoyage')),
            ],
        ),
        migrations.AddField(
            model_name='ordremission',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.vehicule'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
