# Generated by Django 5.2 on 2025-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_alter_vehicule_type_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
