# Generated by Django 5.2 on 2025-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0010_alter_hotel_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ville', models.JSONField(default=list)),
                ('pays', models.JSONField(default=list)),
                ('reference', models.JSONField(default=list)),
                ('type_da', models.JSONField(default=list)),
                ('nom_reservation', models.JSONField(default=list)),
                ('horaire', models.JSONField(default=list)),
            ],
        ),
    ]
