# Generated by Django 5.2 on 2025-08-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_add_initial_languages'),
        ('b2b', '0011_languagemapping'),
    ]

    operations = [
    ]
