# Generated by Django 5.2 on 2025-08-15 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0012_merge_0011_add_initial_languages_0011_languagemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('A', 'Arrivée'), ('D', 'Départ')], max_length=1)),
                ('date', models.DateField()),
                ('aeroport', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_mouvement', to='b2b.agencevoyage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheMouvementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_items', to='b2b.dossier')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.fichemouvement')),
            ],
        ),
    ]
