# Generated by Django 5.2 on 2025-09-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_fichemouvement_fichemouvementitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('premission', 'date_debut', 'date_fin'), name='uniq_mission_premission_date_range'),
        ),
    ]
