# Generated by Django 5.2 on 2025-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0014_alter_mission_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordremission',
            name='reference',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
