# Generated by Django 5.2 on 2025-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0015_alter_ordremission_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='tour_operateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
