# Generated by Django 5.2 on 2025-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0016_dossier_tour_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ordre_mission_genere',
            field=models.BooleanField(default=False),
        ),
    ]
