# Generated by Django 5.2.6 on 2025-09-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0017_mission_ordre_mission_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rentout', 'Rentout'), ('rideshare', 'Rideshare')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('seats_total', models.PositiveIntegerField(blank=True, null=True)),
                ('seats_reserved', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='TND', max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_offers', to='b2b.agencevoyage')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='b2b.vehicule')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'start', 'end', 'active', 'is_public'], name='b2b_vehicle_mode_4f6a30_idx')],
            },
        ),
    ]
