# Generated by Django 5.2.6 on 2025-09-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0018_dossier_observation_vehicleoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicleoffer',
            name='price_per_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleoffer',
            name='price_per_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EXCURSION', 'Excursion'), ('NAVETTE', 'Navette')], max_length=10)),
                ('titre', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('avec_repas', models.BooleanField(default=False)),
                ('duree', models.CharField(blank=True, choices=[('HALF', 'Demi-journée'), ('FULL', 'Journée entière')], default='', max_length=8)),
                ('theme', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='b2b.agencevoyage')),
                ('zone_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_depart', to='b2b.zone')),
                ('zone_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_destination', to='b2b.zone')),
                ('zone_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_origine', to='b2b.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='b2b.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReservationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('nb_adultes', models.PositiveIntegerField(default=0)),
                ('nb_enfants', models.PositiveIntegerField(default=0)),
                ('prix_adulte_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_enfant_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_produits', to='b2b.agencevoyage')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_produits', to='b2b.dossier')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_sources', to='b2b.mission')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='b2b.produit')),
                ('zone_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_pickup', to='b2b.zone')),
            ],
        ),
        migrations.AddField(
            model_name='vehicleoffer',
            name='destination_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_destination', to='b2b.zone'),
        ),
        migrations.AddField(
            model_name='vehicleoffer',
            name='origin_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_origin', to='b2b.zone'),
        ),
        migrations.CreateModel(
            name='ProduitTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_adulte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_enfant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tarifs', to='b2b.agencevoyage')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='b2b.produit')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tarifs', to='b2b.zone')),
            ],
            options={
                'unique_together': {('produit', 'agence', 'zone')},
            },
        ),
    ]
