# Generated by Django 5.2.6 on 2025-09-23 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0019_zone_vehicleoffer_price_per_adult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['reference']},
        ),
        migrations.AlterModelOptions(
            name='fichemouvement',
            options={'ordering': ['-date', '-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_debut', 'reference']},
        ),
        migrations.AlterUniqueTogether(
            name='fichemouvementitem',
            unique_together={('fiche', 'dossier')},
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['agence'], name='b2b_dossier_agence__259eae_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['heure_arrivee'], name='b2b_dossier_heure_a_555b46_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['heure_depart'], name='b2b_dossier_heure_d_c023d1_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['tour_operateur'], name='b2b_dossier_tour_op_363029_idx'),
        ),
        migrations.AddIndex(
            model_name='fichemouvement',
            index=models.Index(fields=['agence', 'date'], name='b2b_fichemo_agence__b7f484_idx'),
        ),
        migrations.AddIndex(
            model_name='fichemouvement',
            index=models.Index(fields=['type'], name='b2b_fichemo_type_b0cca4_idx'),
        ),
        migrations.AddIndex(
            model_name='fichemouvement',
            index=models.Index(fields=['aeroport'], name='b2b_fichemo_aeropor_71f974_idx'),
        ),
        migrations.AddIndex(
            model_name='fichemouvementitem',
            index=models.Index(fields=['fiche'], name='b2b_fichemo_fiche_i_9c98fa_idx'),
        ),
        migrations.AddIndex(
            model_name='fichemouvementitem',
            index=models.Index(fields=['dossier'], name='b2b_fichemo_dossier_1fb184_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['date_debut'], name='b2b_mission_date_de_ad1456_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['date_fin'], name='b2b_mission_date_fi_1aa090_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['ordre_mission_genere'], name='b2b_mission_ordre_m_a53e03_idx'),
        ),
    ]
