# Generated by Django 5.2.6 on 2025-09-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0020_alter_dossier_options_alter_fichemouvement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichemouvement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='b2b_dossier_agence__259eae_idx',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='b2b_dossier_heure_a_555b46_idx',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='b2b_dossier_heure_d_c023d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='b2b_dossier_tour_op_363029_idx',
        ),
        migrations.RemoveIndex(
            model_name='fichemouvement',
            name='b2b_fichemo_agence__b7f484_idx',
        ),
        migrations.RemoveIndex(
            model_name='fichemouvement',
            name='b2b_fichemo_type_b0cca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='fichemouvement',
            name='b2b_fichemo_aeropor_71f974_idx',
        ),
        migrations.RemoveIndex(
            model_name='fichemouvementitem',
            name='b2b_fichemo_fiche_i_9c98fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='fichemouvementitem',
            name='b2b_fichemo_dossier_1fb184_idx',
        ),
        migrations.RemoveIndex(
            model_name='mission',
            name='b2b_mission_date_de_ad1456_idx',
        ),
        migrations.RemoveIndex(
            model_name='mission',
            name='b2b_mission_date_fi_1aa090_idx',
        ),
        migrations.RemoveIndex(
            model_name='mission',
            name='b2b_mission_ordre_m_a53e03_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fichemouvementitem',
            unique_together=set(),
        ),
    ]
