# Generated by Django 5.2.6 on 2025-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0021_alter_dossier_options_alter_fichemouvement_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fichemouvementitem',
            constraint=models.UniqueConstraint(fields=('dossier',), name='uniq_fiche_item_per_dossier_global'),
        ),
    ]
