# Generated by Django 5.2.6 on 2025-09-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0022_fichemouvementitem_uniq_fiche_item_per_dossier_global'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fichemouvementitem',
            name='uniq_fiche_item_per_dossier_global',
        ),
    ]
