# Generated by Django 5.2.6 on 2025-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0023_remove_fichemouvementitem_uniq_fiche_item_per_dossier_global'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fichemouvementitem',
            index=models.Index(fields=['dossier'], name='b2b_fichemo_dossier_1fb184_idx'),
        ),
    ]
