# Generated by Django 5.2.6 on 2025-09-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0024_fichemouvementitem_b2b_fichemo_dossier_1fb184_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='hotel_schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
