# Generated by Django 5.2.6 on 2025-09-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0025_fichemouvement_hotel_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordremission',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='b2b.fichemouvement'),
        ),
    ]
