# Generated by Django 5.2.6 on 2025-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0026_ordremission_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='import_batch',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
