# Generated by Django 5.2.6 on 2025-10-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0027_dossier_import_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='import_batch',
        ),
    ]
