# Generated by Django 5.2.6 on 2025-10-09 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0028_remove_dossier_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='b2b.agencevoyage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.importbatch')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_items', to='b2b.dossier')),
            ],
            options={
                'unique_together': {('batch', 'dossier')},
            },
        ),
    ]
