# Generated by Django 5.2.6 on 2025-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0029_importbatch_importbatchitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fichemouvementitem',
            constraint=models.UniqueConstraint(fields=('fiche', 'dossier'), name='uniq_item_fiche_dossier'),
        ),
    ]
