# Generated by Django 5.2.6 on 2025-10-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0030_fichemouvementitem_uniq_item_fiche_dossier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fichemouvementitem',
            name='uniq_item_fiche_dossier',
        ),
        migrations.AlterUniqueTogether(
            name='importbatchitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='produittarif',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fichemouvementitem',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_items', to='b2b.dossier'),
        ),
        migrations.AddConstraint(
            model_name='fichemouvementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('dossier__isnull', False)), fields=('fiche', 'dossier'), name='uniq_item_fiche_dossier'),
        ),
        migrations.AddConstraint(
            model_name='importbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'dossier'), name='uniq_import_batch_dossier'),
        ),
        migrations.AddConstraint(
            model_name='produittarif',
            constraint=models.UniqueConstraint(fields=('produit', 'agence', 'zone'), name='uniq_produit_tarif_agence_zone'),
        ),
    ]
