# Generated by Django 5.2 on 2025-10-30 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_alter_agencevoyage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichemouvement',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='fichemouvement',
            old_name='titular',
            new_name='titulaire',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='compagnie',
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='adulte',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='bebe',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='ref',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_mouvement', to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='pax',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('adminagence', 'Admin Agence')], default='adminagence', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
