# Generated by Django 5.2 on 2025-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0017_agencyapplication_patente_doc_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='adresse',
            field=models.CharField(blank=True, help_text='Adresse du chauffeur', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='statut',
            field=models.CharField(choices=[('dispo', 'Disponible'), ('occupe', 'Occupé')], default='dispo', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='adresse',
            field=models.CharField(blank=True, help_text='Adresse de stationnement / base du véhicule', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('dispo', 'Disponible'), ('occupe', 'Occupé')], default='dispo', max_length=10),
        ),
    ]
