# Generated by Django 5.2 on 2025-11-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0025_rentoutrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='annee_mise_en_circulation',
            field=models.PositiveIntegerField(blank=True, help_text='Année de première mise en circulation', null=True),
        ),
    ]
