# Generated by Django 5.2 on 2025-11-30 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0026_alter_vehicule_annee_mise_en_circulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.mission'),
        ),
    ]
