# Generated by Django 5.2 on 2025-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0057_missionressource_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='adresse',
            field=models.CharField(blank=True, help_text="Adresse du chauffeur (localisation courante si pas d'affectation)", max_length=255, null=True),
        ),
    ]
