# Generated by Django 5.2 on 2026-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0065_alter_agencyapplication_rep_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
