# Generated by Django 5.2 on 2025-10-29 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.TextField(blank=True, default='')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('roles_mask', models.PositiveSmallIntegerField(default=1, help_text='Flags: 1=agence, 2=client, 4=fournisseur, 8=succursale (somme possible).')),
            ],
            options={
                'verbose_name': 'Agence de voyage',
                'verbose_name_plural': 'Agences de voyage',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ville', models.JSONField(default=list)),
                ('pays', models.JSONField(default=list)),
                ('reference', models.JSONField(default=list)),
                ('type_da', models.JSONField(default=list)),
                ('nom_reservation', models.JSONField(default=list)),
                ('horaire', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Touriste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('vol_arrivee', models.CharField(max_length=50)),
                ('hotel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='b2b.agencevoyage')),
            ],
        ),
        migrations.CreateModel(
            name='FicheMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('A', 'Arrivée'), ('D', 'Départ')], max_length=1)),
                ('date', models.DateField()),
                ('aeroport', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_schedule', models.JSONField(blank=True, default=list, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_mouvement', to='b2b.agencevoyage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('horaires', models.CharField(blank=True, default='', max_length=20)),
                ('provenance', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('sens', models.CharField(choices=[('A', 'ARRIVÉE'), ('D', 'DÉPART')], max_length=1)),
                ('numero_vol', models.CharField(blank=True, default='', max_length=50)),
                ('client_to', models.CharField(blank=True, default='', max_length=255)),
                ('hotel', models.CharField(blank=True, default='', max_length=255)),
                ('ref', models.CharField(blank=True, default='', max_length=100)),
                ('titulaire', models.CharField(blank=True, default='', max_length=255)),
                ('pax', models.PositiveIntegerField(default=0)),
                ('adulte', models.PositiveIntegerField(default=0)),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('bb_gratuit', models.PositiveIntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='b2b.agencevoyage')),
                ('fiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='b2b.fichemouvement')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='b2b.agencevoyage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.IntegerField()),
                ('field', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('raw_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='b2b.importbatch')),
            ],
            options={
                'ordering': ['excel_row'],
            },
        ),
        migrations.CreateModel(
            name='PreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('trajet_prevu', models.CharField(max_length=255)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_missions', to='b2b.agencevoyage')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_missions', to='b2b.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('details', models.TextField(blank=True)),
                ('ordre_mission_genere', models.BooleanField(default=False)),
                ('premission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='b2b.premission')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EXCURSION', 'Excursion'), ('NAVETTE', 'Navette')], max_length=10)),
                ('titre', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('avec_repas', models.BooleanField(default=False)),
                ('duree', models.CharField(blank=True, choices=[('HALF', 'Demi-journée'), ('FULL', 'Journée entière')], default='', max_length=8)),
                ('theme', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='b2b.agencevoyage')),
                ('zone_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_depart', to='b2b.zone')),
                ('zone_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_destination', to='b2b.zone')),
                ('zone_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_origine', to='b2b.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='b2b.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('adminagence', 'Admin Agence')], max_length=20)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='b2b.agencevoyage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succursales', to='b2b.agencevoyage')),
            ],
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='tour_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='b2b.touroperateur'),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('MICROBUS', 'Microbus'), ('4x4', '4X4')], max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='b2b.agencevoyage')),
            ],
        ),
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_depart', models.DateTimeField()),
                ('date_retour', models.DateTimeField()),
                ('trajet', models.CharField(max_length=255)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.chauffeur')),
                ('fiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='b2b.fichemouvement')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='b2b.mission')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rentout', 'Rentout'), ('rideshare', 'Rideshare')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('seats_total', models.PositiveIntegerField(blank=True, null=True)),
                ('seats_reserved', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='TND', max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_offers', to='b2b.agencevoyage')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='b2b.vehicule')),
                ('destination_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_destination', to='b2b.zone')),
                ('origin_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_origin', to='b2b.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('nb_adultes', models.PositiveIntegerField(default=0)),
                ('nb_enfants', models.PositiveIntegerField(default=0)),
                ('prix_adulte_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_enfant_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_produits', to='b2b.agencevoyage')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_produits', to='b2b.dossier')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_sources', to='b2b.mission')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='b2b.produit')),
                ('zone_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_pickup', to='b2b.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_adulte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_enfant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tarifs', to='b2b.agencevoyage')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='b2b.produit')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_tarifs', to='b2b.zone')),
            ],
        ),
        migrations.CreateModel(
            name='FicheMouvementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_items', to='b2b.dossier')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.fichemouvement')),
            ],
            options={
                'indexes': [models.Index(fields=['dossier'], name='b2b_fichemo_dossier_1fb184_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dossier__isnull', False)), fields=('fiche', 'dossier'), name='uniq_item_fiche_dossier')],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.importbatch')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_items', to='b2b.dossier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'dossier'), name='uniq_import_batch_dossier')],
            },
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('premission', 'date_debut', 'date_fin'), name='uniq_mission_premission_date_range'),
        ),
        migrations.AddIndex(
            model_name='succursale',
            index=models.Index(fields=['agence', 'nom'], name='b2b_succurs_agence__3ef04d_idx'),
        ),
        migrations.AddConstraint(
            model_name='succursale',
            constraint=models.UniqueConstraint(fields=('agence', 'nom'), name='uniq_succursale_nom_par_agence'),
        ),
        migrations.AddIndex(
            model_name='agencevoyage',
            index=models.Index(fields=['nom'], name='b2b_agencev_nom_ee6932_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleoffer',
            index=models.Index(fields=['mode', 'start', 'end', 'active', 'is_public'], name='b2b_vehicle_mode_4f6a30_idx'),
        ),
        migrations.AddConstraint(
            model_name='produittarif',
            constraint=models.UniqueConstraint(fields=('produit', 'agence', 'zone'), name='uniq_produit_tarif_agence_zone'),
        ),
    ]
