# Generated by Django 5.2 on 2025-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0015_agencevoyage_code_categorie_agencevoyage_code_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyapplication',
            options={},
        ),
        migrations.AddField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé')], default='disponible', max_length=20),
        ),
    ]
