# Generated by Django 5.2 on 2025-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0018_chauffeur_adresse_chauffeur_statut_vehicule_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='east',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='north',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='radius_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='south',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='type',
            field=models.CharField(blank=True, default='circle', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='ville',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='west',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='code_postal',
        ),
    ]
