# Generated by Django 5.2 on 2025-12-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0029_rename_depart_adresse_excursiontemplate_depart_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursiontemplate',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursion_templates', to='b2b.agencevoyage'),
        ),
    ]
