# Generated by Django 5.2 on 2025-12-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0037_historiquetransformation_alter_dossier_options_and_more'),
    ]

    operations = [
    ]
