# Generated by Django 5.2 on 2025-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0040_remove_dossier_observation_alter_dossier_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dossiers_refs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='dossiers_refs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
