# Generated by Django 5.2 on 2025-12-16 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0043_fichemouvement_hotel_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichemouvement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='historiquetransformation',
            options={'ordering': ['-date_transformation']},
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.mission'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='fiche_de_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.fichemouvement'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.mission'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='transformed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='type_transformation',
            field=models.CharField(help_text='Ex: DOSSIER->FICHE, FICHE->MISSION', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_converted_from_fiche',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='pax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
