# Generated by Django 5.2 on 2025-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0050_alter_historiquetransformation_transformed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
