# Generated by Django 5.2 on 2026-01-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0064_agencyotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyapplication',
            name='rep_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
