# Generated by Django 5.2 on 2025-11-05 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_agencevoyage_options_alter_chauffeur_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='chauffeur',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='fiche',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='trajet',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='aeroport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='b2b.agencevoyage'),
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_vol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='numero_vol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]

