# Generated by Django 5.2 on 2025-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_backfill_mission_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('T', 'Transfert'), ('E', 'Excursion'), ('N', 'Navette')], default='T', max_length=1),
        ),
    ]

