# Generated by Django 5.2 on 2025-11-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_fichemouvement_hotel_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('lieu_depart', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu_arrivee', models.CharField(blank=True, max_length=255, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='b2b.chauffeur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='b2b.mission')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='b2b.vehicule')),
            ],
            options={
                'ordering': ['date_heure_debut'],
            },
        ),
    ]

