# Generated by Django 5.2 on 2025-11-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_demandeinscriptionagence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('rne', models.CharField(max_length=100)),
                ('code_fiscal', models.CharField(max_length=100)),
                ('code_categorie', models.CharField(max_length=100)),
                ('etab_secondaire', models.CharField(max_length=100)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='agencies/logos/')),
                ('company_country', models.CharField(max_length=100)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=50)),
                ('rep_prenom', models.CharField(max_length=100)),
                ('rep_nom', models.CharField(max_length=100)),
                ('rep_cin', models.CharField(max_length=50)),
                ('rep_date_naissance', models.DateField()),
                ('rep_photo_file', models.ImageField(blank=True, null=True, upload_to='agencies/reps/')),
                ('rep_email', models.EmailField(max_length=254)),
                ('rep_phone', models.CharField(max_length=50)),
                ('otp_delivery', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], max_length=10)),
                ('otp_code', models.CharField(blank=True, help_text='Code saisi par le client (Ã  valider cÃ´tÃ© plateforme / gestionnaire).', max_length=10, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'ValidÃ©e'), ('refusee', 'RefusÃ©e')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_applications', to='b2b.agencevoyage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_applications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

