# Generated by Django 5.2 on 2025-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_agencyapplication_options_vehicule_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyapplication',
            name='patente_doc_file',
            field=models.FileField(blank=True, null=True, upload_to='agences/patente_docs/', verbose_name='Patente / Registre de commerce (PDF/image)'),
        ),
        migrations.AddField(
            model_name='agencyapplication',
            name='rne_doc_file',
            field=models.FileField(blank=True, null=True, upload_to='agences/rne_docs/', verbose_name='Document RNE (PDF/image)'),
        ),
    ]

