# Generated by Django 5.2 on 2025-11-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_zone_options_zone_code_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeTarifZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('microbus', 'Microbus'), ('4x4', '4x4')], max_length=32)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devise', models.CharField(default='TND', max_length=3)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_vehicules', to='b2b.zone')),
            ],
            options={
                'unique_together': {('zone', 'type_code')},
            },
        ),
        migrations.DeleteModel(
            name='TarifTypeVehicule',
        ),
    ]

