# Generated by Django 5.2 on 2025-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_vehiculetarifzone_delete_tariftypevehicule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculetarifzone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiculetarifzone',
            name='aeroport',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vehiculetarifzone',
            unique_together={('aeroport', 'zone', 'type_code')},
        ),
    ]

