# Generated by Django 5.2 on 2025-12-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_fichemouvement_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('theme', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
                ('type_duree', models.CharField(choices=[('HALF_DAY', '1/2 journÃ©e'), ('FULL_DAY', 'JournÃ©e complÃ¨te'), ('MULTI_DAY', 'Plusieurs jours')], default='HALF_DAY', help_text="1/2 journÃ©e, journÃ©e complÃ¨te ou plus d'une journÃ©e.", max_length=20)),
                ('repas_matin', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('repas_soir', models.BooleanField(default=False)),
                ('depart_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('depart_lat', models.FloatField(blank=True, null=True)),
                ('depart_lng', models.FloatField(blank=True, null=True)),
                ('retour_adresse', models.CharField(blank=True, help_text="Pour les excursions de plusieurs jours, emplacement de retour (zone d'hÃ´tels...).", max_length=255, null=True)),
                ('retour_lat', models.FloatField(blank=True, null=True)),
                ('retour_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursion_templates', to='b2b.agencevoyage')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_meal_stop_matin', models.BooleanField(default=False)),
                ('is_meal_stop_midi', models.BooleanField(default=False)),
                ('is_meal_stop_soir', models.BooleanField(default=False)),
                ('duree_arret_minutes', models.PositiveIntegerField(default=0, help_text="DurÃ©e approximative de l'arrÃªt Ã  cette Ã©tape.")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='b2b.excursiontemplate')),
            ],
            options={
                'ordering': ['template', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_depart', models.TimeField()),
                ('heure_retour_estimee', models.TimeField(blank=True, null=True)),
                ('repas_matin', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('repas_soir', models.BooleanField(default=False)),
                ('vehicle_source', models.CharField(choices=[('INTERNAL', 'Ma flotte'), ('RENTOUT', 'Rentout')], default='INTERNAL', max_length=20)),
                ('nb_participants', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('PLANNED', 'PrÃ©vu'), ('CONFIRMED', 'ConfirmÃ©'), ('IN_PROGRESS', 'En cours'), ('DONE', 'TerminÃ©'), ('CANCELLED', 'AnnulÃ©')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='b2b.agencevoyage')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='b2b.chauffeur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_events', to='b2b.mission')),
                ('vehicule_interne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursions_internes', to='b2b.vehicule')),
                ('vehicule_rentout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursions_rentout', to='b2b.vehicule')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='b2b.excursiontemplate')),
            ],
        ),
    ]

