# Generated by Django 5.2 on 2025-12-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_excursiontemplate_excursionstep_excursionevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursiontemplate',
            old_name='depart_adresse',
            new_name='depart_label',
        ),
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='repas_matin',
        ),
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='repas_midi',
        ),
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='repas_soir',
        ),
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='retour_adresse',
        ),
        migrations.AddField(
            model_name='excursiontemplate',
            name='depart_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excursiontemplate',
            name='nb_jours',
            field=models.PositiveIntegerField(default=1, help_text='UtilisÃ© seulement si type = MULTI'),
        ),
        migrations.AddField(
            model_name='excursiontemplate',
            name='repas_inclus',
            field=models.BooleanField(default=False, help_text="Cocher si l'excursion inclut un ou plusieurs repas"),
        ),
        migrations.AddField(
            model_name='excursiontemplate',
            name='retour_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excursiontemplate',
            name='retour_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_templates', to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='depart_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='depart_lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='type_duree',
            field=models.CharField(choices=[('HALF', '1/2 journÃ©e'), ('FULL', 'JournÃ©e complÃ¨te'), ('MULTI', 'Plusieurs jours')], default='HALF', max_length=10),
        ),
    ]

