# Generated by Django 5.2 on 2025-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_excursiontemplate_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='agence',
        ),
        migrations.RemoveField(
            model_name='excursiontemplate',
            name='theme',
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='depart_label',
            field=models.CharField(blank=True, help_text='Point de dÃ©part (ex : Agence, hÃ´tel, lieu de rendez-vous).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='depart_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excursiontemplate',
            name='depart_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]

