# Generated by Django 5.2 on 2025-12-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_vehicule_last_lat_vehicule_last_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursiontemplate',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursion_templates', to='b2b.agencevoyage'),
        ),
    ]

