# Generated by Django 5.2 on 2025-12-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_excursiontemplate_agence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiculetarifzone',
            name='tarif_type_ou_vehicule',
        ),
        migrations.RemoveConstraint(
            model_name='vehiculetarifzone',
            name='uniq_tarif_vehicule',
        ),
        #migrations.RemoveConstraint(
         #   model_name='vehiculetarifzone',
          #  name='uniq_tarif_general_par_agence',
        #),
    ]

