# Generated by Django 5.2 on 2025-12-15 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_remove_dossier_historique_transformation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='observation',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='hotel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.hotel'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='is_transformed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='type_mouvement',
            field=models.CharField(choices=[('A', 'ArrivÃ©e'), ('D', 'DÃ©part'), ('L', 'ArrivÃ©e locale'), ('S', 'Sortie')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='zone_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.zone'),
        ),
    ]

