# Generated by Django 5.2 on 2025-12-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_historiquetransformation_fiche_de_mouvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquetransformation',
            name='fiche_de_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.fichemouvement'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='b2b.dossier'),
        ),
    ]

