# Generated by Django 5.2 on 2025-12-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_hotfix_add_mission_column'),
        ('apps', '0047_historiquetransformation_fiche_de_mouvement_and_more'),
    ]

    operations = [
    ]

