# Generated by Django 5.2 on 2025-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_dossier_code_postal_dossier_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]

