# Generated by Django 5.2 on 2025-12-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0054_hotel_created_at_hotel_formatted_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='agence',
        ),
    ]

