# Generated by Django 5.2 on 2025-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0055_remove_zone_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]

