# Generated by Django 5.2 on 2025-12-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0059_missionressource_b2b_mission_is_dele_aa9294_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='ordre_mission',
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_mission', to='b2b.mission'),
        ),
    ]

