# Generated by Django 5.2 on 2025-10-30 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_agencevoyage_user_alter_agencevoyage_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencevoyage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agence', to=settings.AUTH_USER_MODEL),
        ),
    ]
