# Generated by Django 5.2 on 2025-10-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_fichemouvement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemouvement',
            name='aeroport',
        ),
    ]
