# Generated by Django 5.2 on 2025-10-31 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_fichemouvement_aeroport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencevoyage',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'ordering': ['agence__nom', 'nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='languagemapping',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_depart', '-id']},
        ),
        migrations.AlterModelOptions(
            name='ordremission',
            options={'ordering': ['-date_generation']},
        ),
        migrations.AlterModelOptions(
            name='succursale',
            options={'ordering': ['agence__nom', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='touroperateur',
            options={'ordering': ['nom'], 'verbose_name': 'Tour Opérateur', 'verbose_name_plural': 'Tour Opérateurs'},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['agence__nom', 'immatriculation']},
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='hotel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.agencevoyage'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('nom', 'code_postal')},
            },
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='zone_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.zone'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='b2b.zone'),
        ),
    ]
