# Generated by Django 5.2 on 2025-11-10 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_mission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('type_mouvement', models.CharField(blank=True, choices=[('A', 'Arrivée'), ('D', 'Départ')], max_length=1, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('horaires', models.TimeField(blank=True, null=True)),
                ('provenance', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_vol', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('titulaire', models.CharField(blank=True, max_length=255, null=True)),
                ('pax', models.PositiveIntegerField(default=0)),
                ('adulte', models.PositiveIntegerField(default=0)),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('bb_gratuit', models.PositiveIntegerField(default=0)),
                ('hotel', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='b2b.agencevoyage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('fiches', models.ManyToManyField(blank=True, related_name='dossiers', to='b2b.fichemouvement')),
                ('hotel_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='b2b.hotel')),
                ('zone_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='b2b.zone')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('agence', 'reference'), name='uniq_dossier_ref_par_agence')],
            },
        ),
    ]
