# Generated by Django 5.2 on 2025-11-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='hotel_schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='horaires',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche', to='b2b.mission'),
        ),
    ]
