# Generated by Django 5.2 on 2025-11-14 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_missionressource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscriptionAgence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_agence', models.CharField(max_length=100)),
                ('matricule_fiscale', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, default='')),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('cin_responsable', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', help_text='Statut de la demande (en attente / validée / refusée).', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, help_text='Agence finalement créée à partir de la demande (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_inscription', to='b2b.agencevoyage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_inscription_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
