# Generated by Django 5.2 on 2025-11-15 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_agencyapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencevoyage',
            name='code_categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='code_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='etab_secondaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='agencies/logos/'),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rep_prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='rne',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RNE'),
        ),
        migrations.AddField(
            model_name='agencevoyage',
            name='telephone_urgence_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agencyapplication',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_applications_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agencevoyage',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='agencevoyage',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_origine', to='b2b.agencevoyage'),
        ),
        migrations.AlterField(
            model_name='agencyapplication',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='DemandeInscriptionAgence',
        ),
    ]
