# Generated by Django 5.2 on 2025-11-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_zone_options_alter_zone_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemouvement',
            name='mission',
        ),
    ]
