# Generated by Django 5.2 on 2025-11-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_fichemouvement_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='zone',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TarifTypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('microbus', 'Microbus'), ('4x4', '4x4')], max_length=20)),
                ('devise', models.CharField(default='TND', max_length=3)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_demi_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_vehicules', to='b2b.agencevoyage')),
            ],
            options={
                'verbose_name': 'Tarif type véhicule',
                'verbose_name_plural': 'Tarifs type véhicule',
                'ordering': ['agence__nom', 'type_code'],
                'constraints': [models.UniqueConstraint(fields=('agence', 'type_code'), name='uniq_tarif_type_par_agence')],
            },
        ),
    ]
