# Generated by Django 5.2 on 2025-11-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_alter_vehiculetarifzone_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculetarifzone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiculetarifzone',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehiculetarifzone',
            name='aeroport',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculetarifzone',
            name='type_code',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('microbus', 'Microbus'), ('4x4', '4x4')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculetarifzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ville',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehiculetarifzone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_code__isnull', False), ('vehicule__isnull', True)), models.Q(('type_code__isnull', True), ('vehicule__isnull', False)), _connector='OR'), name='tarif_type_ou_vehicule'),
        ),
        migrations.AddConstraint(
            model_name='vehiculetarifzone',
            constraint=models.UniqueConstraint(condition=models.Q(('type_code__isnull', False)), fields=('aeroport', 'zone', 'type_code'), name='uniq_tarif_general'),
        ),
        migrations.AddConstraint(
            model_name='vehiculetarifzone',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicule__isnull', False)), fields=('aeroport', 'zone', 'vehicule'), name='uniq_tarif_vehicule'),
        ),
    ]
