# Generated by Django 5.2 on 2025-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_remove_excursiontemplate_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='adresse',
            field=models.CharField(blank=True, help_text='Adresse actuelle du véhicule (agence, hôtel, aéroport...)', max_length=255, null=True),
        ),
    ]
