# Generated by Django 5.2 on 2025-12-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_remove_vehiculetarifzone_tarif_type_ou_vehicule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiculetarifzone',
            name='uniq_tarif_general',
        ),

        # ⚠️ ICI : on ne refait pas l'ALTER TABLE, on met juste à jour l'état Django
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Rien à faire : la colonne mission_id existe déjà en base
            ],
            state_operations=[
                migrations.AddField(
                    model_name='rentoutrequest',
                    name='mission',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rentout_requests',
                        to='b2b.mission',
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),

        migrations.AlterField(
            model_name='vehiculetarifzone',
            name='vehicule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tarifs_zones',
                to='b2b.vehicule',
            ),
        ),
    ]
