# Generated by Django 5.2 on 2025-12-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_remove_vehiculetarifzone_uniq_tarif_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculetarifzone',
            name='agence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_vehicules_par_zone', to='b2b.agencevoyage'),
            preserve_default=False,
        ),
    ]
