# Generated by Django 5.2 on 2025-12-12 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_vehiculetarifzone_agence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transformation', models.DateTimeField(auto_now_add=True)),
                ('type_transformation', models.CharField(help_text='Type de transformation (Dossier -> Fiche de Mouvement -> Mission)', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichemouvement',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dossier',
            name='uniq_dossier_ref_par_agence',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='fiches',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='adulte',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='bebe',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='enfants',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='hotel_fk',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='hotel_schedule',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='zone_fk',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='heure_vol',
        ),
        migrations.AddField(
            model_name='dossier',
            name='fiche_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='b2b.fichemouvement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='is_transformed',
            field=models.BooleanField(default=False, help_text='Indique si ce dossier a été transformé en fiche de mouvement'),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='is_converted_to_mission',
            field=models.BooleanField(default=False, help_text='Indique si cette fiche a été convertie en mission'),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='reference',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='b2b.chauffeur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='horaires',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_converted_from_fiche',
            field=models.BooleanField(default=False, help_text="Indique si cette mission a été générée à partir d'une fiche de mouvement"),
        ),
        migrations.AddField(
            model_name='mission',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='ordre_mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_detail', to='b2b.ordremission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pax',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='provenance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='reference',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='b2b.vehicule'),
        ),
        migrations.AddField(
            model_name='mission',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='b2b.hotel'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_mission_relation', to='b2b.mission'),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.dossier'),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='fiche_de_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.fichemouvement'),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.mission'),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='transformed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='historique_transformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='b2b.historiquetransformation'),
        ),
    ]
