# Generated by Django 5.2 on 2025-12-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20251212_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='historique_transformation',
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='b2b.dossier'),
        ),
    ]
