# Generated by Django 5.2 on 2025-12-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_dossier_dossiers_refs_fichemouvement_dossiers_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemouvement',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='dossiers_refs',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='is_converted_to_mission',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='titulaire',
        ),
        migrations.RemoveField(
            model_name='fichemouvement',
            name='ville',
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='adulte',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='bebe',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichemouvement',
            name='enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='pax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichemouvement',
            name='type',
            field=models.CharField(max_length=1),
        ),
    ]
