# Generated by Django 5.2 on 2025-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_remove_fichemouvement_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemouvement',
            name='hotel_schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
