# Generated by Django 5.2 on 2025-12-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_merge_20251216_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquetransformation',
            name='mission',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.mission'),
        ),
    ]
