# Generated by Django 5.2 on 2025-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0056_remove_hotel_created_at_remove_hotel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionressource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionressource',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='missionressource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('vehicule__isnull', False)), fields=('mission', 'vehicule'), name='uniq_mission_vehicule'),
        ),
        migrations.AddConstraint(
            model_name='missionressource',
            constraint=models.UniqueConstraint(condition=models.Q(('chauffeur__isnull', False), ('is_deleted', False)), fields=('mission', 'chauffeur'), name='uniq_mission_chauffeur'),
        ),
    ]
