# Generated by Django 5.2 on 2025-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0058_alter_chauffeur_adresse'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='missionressource',
            index=models.Index(fields=['is_deleted', 'date_heure_debut'], name='b2b_mission_is_dele_aa9294_idx'),
        ),
        migrations.AddIndex(
            model_name='missionressource',
            index=models.Index(fields=['is_deleted', 'date_heure_fin'], name='b2b_mission_is_dele_6802be_idx'),
        ),
        migrations.AddIndex(
            model_name='missionressource',
            index=models.Index(fields=['vehicule', 'is_deleted', 'date_heure_debut'], name='b2b_mission_vehicul_95cf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='missionressource',
            index=models.Index(fields=['chauffeur', 'is_deleted', 'date_heure_debut'], name='b2b_mission_chauffe_874e82_idx'),
        ),
    ]
