# Generated by Django 5.2 on 2025-12-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0060_remove_mission_ordre_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('day', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ordremission',
            name='base_reference',
            field=models.CharField(db_index=True, default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='reference',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ordremission',
            constraint=models.UniqueConstraint(fields=('base_reference', 'version'), name='uniq_om_base_version'),
        ),
        migrations.AddIndex(
            model_name='referencesequence',
            index=models.Index(fields=['prefix', 'day'], name='b2b_referen_prefix_ac8d86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referencesequence',
            unique_together={('prefix', 'day')},
        ),
    ]
