# Generated by Django 5.2 on 2025-12-30 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0061_referencesequence_ordremission_base_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordremission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='ordremission',
            old_name='date_generation',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ordremission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres', to='b2b.mission'),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='reference',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ordremission',
            constraint=models.UniqueConstraint(fields=('mission', 'version'), name='uniq_om_mission_version'),
        ),
    ]
